name: Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'
  pull_request:
    branches:
      - main

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Scan links with lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --base . --accept '200..299,403' --verbose ./
          fail: true
